name: Deploy Web App
on: push
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps: 
      - name: Download coe
        uses: actions/checkout@v3
      - name: investigate host
        run: 
          pwd
          ls -lart
          