name: Output Information
on: 

  pull_request: 
    types: [opened, synchronize]
  workflow_dispatch:
  push:
    branches:
      - main
      - demo_branch
    paths-ignore:
      - '.github/workflows/*'
jobs:
  gather-info:
    runs-on: ubuntu-latest
    steps:
      - name: output info
        run: echo "${{ toJSON( github ) }}"