name: third workflow demo
on: [workflow_dispatch, push]
jobs:
  nginx-deploy-test:
    runs-on: ubuntu-latest
    steps:
        - name: Download code
          uses: actions/checkout@v4
        - name: Download container for testing
          run: 
            docker image pullnginx
            docker image ls
            docker container run -d -p 8080:80 nginx
        - name: Test Web Development
          run: 
             python3 -c "import requests; r=requests.get(`http://localhost:8080`); print(r.status_code)" curl -s localhost:8080
